### ISSUE TITLE
Wwise 2019 support

### ISSUE THREAD

**Issue by Mgamerz** [johnloser-lwi/WwiseTools#13]
Hi,

First off, thanks for this project. I'm a complete newb when it comes to Wwise (I'm not an audio engineer), but I need to automate generating soundbanks. The C# client example AudioKinetic gives is... quite sparse and this looks like it may save me a lot of time :)

Does this still work with 2019 Wwise? My needs are only supported on 2019.1.6 version of Wwise (it's for game modding, so I don't have source control). I see in this issue https://github.com/johnloser-lwi/WwiseTools/issues/9 it lists 2019, but the translation I have from google doesn't make it obvious if it's removing support for older wwise or improving it.

Thanks for all the work you've put in!
Mgamerz

Google translated version:
你好，

首先，感谢这个项目。谈到 Wwise，我完全是个新手（我不是音频工程师），但我需要自动生成音库。 AudioKinetic 给出的 C# 客户端示例是......非常稀疏，这看起来可以为我节省很多时间 :)

这仍然适用于 2019 Wwise 吗？我的需求仅在 2019.1.6 版本的 Wwise 上支持（它是用于游戏改装，所以我没有源代码控制）。我在这个问题 https://github.com/johnloser-lwi/WwiseTools/issues/9 中看到它列出了 2019 年，但我从 google 获得的翻译并没有表明它是否正在删除对旧 wwise 的支持或对其进行改进。

感谢您所做的所有工作！
Mgamerz

**Comment by johnloser-lwi** [comment]
The oldest version I've worked with is 2019.1.7 and most function will work.
I've tried seperate 2021,2022 specifiec functions in different extensions for WwiseUtility class. So most standard functions should work fine in wwise 2019.1.6.

**Comment by Mgamerz** [comment]
I tested and it seems to have worked. Hopefully this will save me a lot of
time generating new audio for an existing game! Wwise is very mouse click
heavy.

Thanks for your work on this!

Mgamerz
